### ISSUE TITLE
Adifruit motor driver burning out M2 , 

### ISSUE THREAD

**Issue by Geordy6of9** [NVIDIA-AI-IOT/jetbot#103]
Hello, 
Adifruit motor driver burning out M2 ,  now on 2 different featherwing. When running basic motion or teleoperation theTB6612FNG chip next too the M1 and M2 terminals is hot enough to burn you. I have replaced the 6 volt DC gear motors, between the first Featherwing and the second.So im stuck any thoughts or ideas??

                                                                           Regards, Geordy

**Comment by DouglasPearless** [comment]
Sounds like the motors are drawing too much current; are there any mechanical issues that might cause friction etc?
