### ISSUE TITLE
Object Following no such file ssd_mobile_v2_coco.engine

### ISSUE THREAD

**Issue by dwight-foster** [NVIDIA-AI-IOT/jetbot#108]
Whenever I try to run the first cell in object following I always get the error [Errno 2] No such file or directory: 'ssd_mobilenet_v2_coco.engine'
I have tried updating the notebooks but it hasn't worked.

**Comment by Jacob-Chew** [comment]
you have to download the engine first. https://drive.google.com/open?id=1RnNBHPDphIOWwHCSfeMCWQ7XN3w3tKFD

**Comment by DwightFoster** [comment]
Where do I download it too?

**Comment by Jacob-Chew** [comment]
just click the link above

**Comment by DwightFoster** [comment]
I have and it still gives me the same error
