### ISSUE TITLE
Object following error: 'tensorrt.tensorrt.Runtime' object has no attribute 'destroy'

### ISSUE THREAD

**Issue by IAmUser4574** [NVIDIA-AI-IOT/jetbot#112]
I ran just the first two lines of the sample:

from jetbot import ObjectDetector
model = ObjectDetector('ssd_mobilenet_v2_coco.engine')

and received this error: 

[TensorRT] WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jetbot-0.3.0-py3.6.egg/jetbot/tensorrt_model.py", line 136, in destroy
    self.runtime.destroy()
AttributeError: 'tensorrt.tensorrt.Runtime' object has no attribute 'destroy'

what went wrong?

**Comment by purn3ndu** [comment]
> The new API no longer includes create and destroy functions. Constructors are used for object creation and destruction is instead handling by scoping (that is, when an object goes out of scope, the garbage collecter can free it). It is also possible to destroy objects manually with del trt_object. Note that del only decrements the reference count of the object - it is still up to the garbage collecter to free it. If you really want to free memory immediately, you can instead invoke the object’s __del__ function.

https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/migrationGuide.html
