### ISSUE TITLE
TensorRT version issue w/ Object Following

### ISSUE THREAD

**Issue by santaimpersonator** [NVIDIA-AI-IOT/jetbot#126]
Currently, when I try to run the Object Following example, I get a version issue when trying to run:
`model = ObjectDetector('ssd_mobilenet_v2_coco.engine')`

The error message I get is:
`[TensorRT] ERROR: The engine plan file is not compatible with this version of TensorRT, expecting library version 5.1.6 got 5.0.6, please rebuild.`

As I was looking up the [instructions to upgrade the library](https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html#upgrading) I noticed that it mentioned [version 5.1.5 being the latest version](https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html#installing). I looked up the [release notes for TensorRT](https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/tensorrt-5.html), but 5.1.6 hasn't been released yet.

Both the error and release notes left me a little confused because when I listed the installed python3 packages:
`pip3 list | grep tensorrt`
I got a response saying I had version 5.1.6.1:
`tensorrt                      5.1.6.1`

Maybe I missed some information somewhere. Any suggestions?

* Is the engine that I downloaded wrong or out of date?
* I [built a new image from scratch](https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Create-SD-Card-Image-From-Scratch) using what I am pretty sure is the latest release. It was in a zip file `jetson-nano-sd-r32.2-2016-07-16.zip` with an image file nameed `sd-blob-b01.img` that I got from [here](https://developer.nvidia.com/jetson-nano-sd-card-image-r322). There is a possibility that I messed up building the image somehow.

**Comment by allengwinn** [comment]
What was the solution here?

**Comment by HabonRoof** [comment]
What was the solution here?

**Comment by jaybdub** [comment]
Hi all,

Currently, the object detection model is pre-built against TensorRT 5.0 that was released with the initial JetPack for Jetson Nano (which JetBot SD card image is based on).  For this reason, the object detection engine must be used against the original JetBot image.

I hope to resolve this limitation soon, but do not have an exact timeline in place.  For the time being, I would recommend using the pre-built JetBot SD card image.  

That said, the model we use is very similarly constructed to that in this repository

https://github.com/AastaNV/TRT_object_detection

Which you may be worth giving a try as well :)

Please let me know if you have any questions.

Best,
John

**Comment by santaimpersonator** [comment]
Is there a simple command line that I can execute to check the version of the SD card image without having to go through the example to test if it is the original image?

Otherwise, where would I find the original image? If I remember correctly, the versions linked in the Wiki were the "updated" images.

-Thanks

**Comment by santaimpersonator** [comment]
@jaybdub I am following the instructions from the other repository.

I got an error when trying to run ```pip3 install numpy pycuda --user```. I've moved past that for the time being, in hopes that my package is "current" enough for this to work.

I was able to download the model, update the graphsurgeon converter, and now I am at the "Execute" part of the run section. I get that I am supposed to supply an image and I assume that it is a picture of the object that I want the Jetbot to follow, but:
- Do you know if I'm I supposed to feed it a set of pictures or just a single picture?
- Also, is there a specific resolution size (i.e. 600x600 pixels or 10MP) or file type (i.e. .jpg, .png, or .bmp) for the image?

Thanks.
***
I tried the pre-built image linked on the [getting started site](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write). It appears to be a later July release and has the same TensorRT version issue. (If it helps, I think I was able to get the version of my image using ```uname -a```; it said ```Linux jetbot 4.9.140-tegra```.)

**Comment by santaimpersonator** [comment]
@allengwinn @HabonRoof @DennisFaucher

One of our customers found a link to where one of the older images was being hosted and reports he was able to get the example working. Check out the [forum post](https://forum.sparkfun.com/viewtopic.php?f=88&t=51549&p=213052#p213052) for details on how to get the object following example working.

@jaybdub 
I would still like to update the engine for users if you can still assist.

**Comment by badVibes--** [comment]
Any update on this? I really don't want to downgrade because the new version promises to enable updates without reflashing and i loose a lot of time redoing things with fresh images. Is there any resource you can recommend so i can fix the network myself?

**Comment by xiepan610** [comment]
@badVibes-- Hi! friend. Have you solved this problem? Any help would be awesomely appreciated.

**Comment by allengwinn** [comment]
I came to the conclusion that trying to run a notebook on today platform 
was just not feasible. I built a similar robot with a Coral Edge TPU and a 
Raspberry Pi :)

**Comment by santaimpersonator** [comment]
Nvidia has since released a [new engine model](https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Examples#example-4---object-following) for their latest image. I am closing this issue.
