### ISSUE TITLE
Install Jetbot on JetPack

### ISSUE THREAD

**Issue by HabonRoof** [NVIDIA-AI-IOT/jetbot#130]
Hi everyone,
I had downloaded the newest JetPack(JP 4.2.2,release date: 2019/08/26),
and I want to build a image file that include all the jetson nano stuff like jetbot, jetracer, donkeycar and the files needed for the nvidia original course.

Is there any method to build a mixed image file? 
So that I can only use one SD card and demo many examples .
P.s My OS is windows 
very thanks~

**Comment by piriboy** [comment]
I also need help on this subject. I installed Jetpack on Jetson Nano and I would like to add Jetbot stuff like, PiOLED and motor drive. I would appreciate any step-by-step help for this. I was so excited about Jetbot project; however, I know very little about linux and coding. Thank you in advance!
