### ISSUE TITLE
jetbot signal kill when running collosion_avoidance train_model.ipyynb

### ISSUE THREAD

**Issue by Ethereal-Coder** [NVIDIA-AI-IOT/jetbot#134]
when trying to run train_model.ipynb --> Train the neural network
im gettting the following error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-e6570b757edc> in <module>
     14         loss = F.cross_entropy(outputs, labels)
     15         loss.backward()
---> 16         optimizer.step()
     17 
     18     test_error_count = 0.0

/usr/local/lib/python3.6/dist-packages/torch/optim/sgd.py in step(self, closure)
     95                     param_state = self.state[p]
     96                     if 'momentum_buffer' not in param_state:
---> 97                         buf = param_state['momentum_buffer'] = torch.zeros_like(p.data)
     98                         buf.mul_(momentum).add_(d_p)
     99                     else:

/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py in handler(signum, frame)
     63         # This following call uses `waitid` with WNOHANG from C side. Therefore,
     64         # Python can still get and update the process status successfully.
---> 65         _error_if_any_worker_fails()
     66         if previous_handler is not None:
     67             previous_handler(signum, frame)

RuntimeError: DataLoader worker (pid 9016) is killed by signal: Killed.

Has anyone run into this issue?

**Comment by jaybdub** [comment]
Hi Ethereal-Coder,

Thanks for reaching out!

I haven't yet had the chance to personally reproduce this issue, but it's possible you're witnessing the issue mentioned in this pull request

https://github.com/NVIDIA-AI-IOT/jetbot/pull/117/files

Could you try manually applying the changes there?  Specifically, replacing the line

```python
train_loss += loss
```

with 

```python
train_loss += float(loss)
```

And the same for ``test_loss`` where appropriate.

Please let me know if this works for you!

Best,
John
