### ISSUE TITLE
Add STEP files for chassis?

### ISSUE THREAD

**Issue by julioasotodv** [NVIDIA-AI-IOT/jetbot#137]
Hi!

I was thinking about modifying a little bit the chassis CAD file, but I just realized that the STEP file for the chassis is unavailable (only the stl)

Would it be possible to upload the STEP file for the chassis?

Thank you so much again. I am definetly enjoying the Jetson Nano platform and ecosystem 😊

**Comment by julioasotodv** [comment]
Ok I just realized that the jetbot_60mm and jetbot_65mm STEP files have all the pieces.

This issue can be closes.

Thank you again!

**Comment by TharakaE15** [comment]
I also need the STEP file do you have that file.
please help
