### ISSUE TITLE
Basic motion import issue

### ISSUE THREAD

**Issue by mike8724** [NVIDIA-AI-IOT/jetbot#149]
I have followed the tutorials to the letter and up until this point haven't had any issues. I have connected to JupyterLab and started programming. The first command after checking the image files are up to date is "from jetbot import Robot"
this command line creates and error
![Annotation 2019-10-15 173354](https://user-images.githubusercontent.com/46674036/66851108-fdce2800-ef71-11e9-9065-47e6d556f227.jpg)
im unable to proceed past this point.

any ideas?

**Comment by David890217** [comment]
I encounter the same problem too.

**Comment by tokk-nv** [comment]
Hi mik8724, David890217,

Thank you for reaching out.

It looks like the cell is incorrectly set as a code cell, not the markdown cell.
You can set it back to code by selecting the cell and change it to code from the toolbar at the top.

Regards,
Chitoku
