### ISSUE TITLE
How to use jetbot.ssd_tensorrt?

### ISSUE THREAD

**Issue by shalahuddinn** [NVIDIA-AI-IOT/jetbot#155]
Hi, 

I want to make a custom object detection project. I want to have the jetbot can detect a red square using my own custom dataset. I have created my model to detect a red box (using my own small dataset, only 30 pictures) using Tensorflow Object Detection API. Therefore I have get my frozen graph. I am using ssd_inception_v2_coco model. I also still have the model.ckpt file.

Now, I don't understand how to convert it into engine using the jetbot.ssd_tensorrt package like what the example of object detection has done. 
<img width="1031" alt="Screen Shot 2019-11-01 at 16 15 25" src="https://user-images.githubusercontent.com/18506906/68172939-af360b80-ffbc-11e9-8486-de01a497d313.png">

**Comment by heartpeng** [comment]
Have you solved it? I have the same question.

**Comment by heartpeng** [comment]
import tensorflow as tf
from jetbot import ssd_tensorrt as trt
checkpoint_path = tf.train.latest_checkpoint(' ')
config_path = ' '
engine_path = ' '
my_uff = trt.ssd_pipeline_to_uff(checkpoint_path,config_path)
my_engine = trt.ssd_uff_to_engine(my_uff)
with open(engine_path,'wb') as f:
    f.write(my_engine.serialize())

I finally solved this problem in this way, but it should be noted that this package must use the previous version of object detection. I used version 0.1
Hope to help you！

**Comment by huangyy1234** [comment]
> [heartpeng](/heartpeng)

Hi, could you share how you installed the object detection package in your jetbot? I ran your code and received an error that says 'No module named 'object detection. Any help will be appreciated.
