### ISSUE TITLE
Cannot connect to jetbot from computer

### ISSUE THREAD

**Issue by HoangLouis** [NVIDIA-AI-IOT/jetbot#160]
I cannot connect to my Jetbot from my laptop's web browser using _https://<jetbot_ip>:8888_
The web browser says that the Jetbot refused the connection from the laptop
![Capture](https://user-images.githubusercontent.com/53995224/68929710-7584b200-07bf-11ea-9a84-7276b7458568.JPG)
Does anyone can help me get through this issue. Thanks a lot!

**Comment by kiwifruit-guo** [comment]
hey, have you already solve the problem?I met the same problem as you.

**Comment by HoangLouis** [comment]
Hi there! I have done with this issue, I will lead you now. The only problem that is I flash the wrong file to my sd card.

If your PioLED is not working, you're actually the same issue as me. These are 2 SD flash files I have download and just only one work right way.
![image](https://user-images.githubusercontent.com/53995224/69495502-33174f80-0efa-11ea-99d3-ae7e6b41efcc.png)

Here is the flash file (right way) that include the PioLED and you can connect easily from your computer to the Jetbot https://github.com/NVIDIA-AI-IOT/jetbot/wiki/software-setup
![image](https://user-images.githubusercontent.com/53995224/69495444-bbe1bb80-0ef9-11ea-8d54-58851f85bc1d.png)

So after done flash, your PioLED will work and you can connect without the error. Hope that can help you!

Best,
Hoang Louis

**Comment by kiwifruit-guo** [comment]
Wow，thanks so much ! 🤓Could please tell me how to get the two SD flash files? I'm looking forward to your reply.
&nbsp;Best wishes.

---Original---

**Comment by HoangLouis** [comment]
Hi there, I just sent you a link above already https://github.com/NVIDIA-AI-IOT/jetbot/wiki/software-setup. Get into this link and click into this, you will have the flash file. 
![image](https://user-images.githubusercontent.com/53995224/69534305-18051800-0fac-11ea-842a-be381aa6c31f.png)

Best,
Hoang Louis

**Comment by kiwifruit-guo** [comment]
Thanks a lot!


 
---Original---
