### ISSUE TITLE
object_following/live_demo fails on first line

### ISSUE THREAD

**Issue by DennisFaucher** [NVIDIA-AI-IOT/jetbot#166]
Hello,

from jetbot import ObjectDetector
model = ObjectDetector('ssd_mobilenet_v2_coco.engine')

fails.  ssd_mobilenet_v2_coco.engine exists and is in the object following directory.

Error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-78c468b59bd4> in <module>
      1 from jetbot import ObjectDetector
      2 
----> 3 model = ObjectDetector('ssd_mobilenet_v2_coco.engine')

/usr/local/lib/python3.6/dist-packages/jetbot-0.3.0-py3.6.egg/jetbot/object_detection.py in __init__(self, engine_path, preprocess_fn)
     26         load_plugins()
     27         self.trt_model = TRTModel(engine_path, input_names=[TRT_INPUT_NAME],
---> 28                                   output_names=[TRT_OUTPUT_NAME, TRT_OUTPUT_NAME + '_1'])
     29         self.preprocess_fn = preprocess_fn
     30 

/usr/local/lib/python3.6/dist-packages/jetbot-0.3.0-py3.6.egg/jetbot/tensorrt_model.py in __init__(self, engine_path, input_names, output_names, final_shapes)
     57         with open(engine_path, 'rb') as f:
     58             self.engine = self.runtime.deserialize_cuda_engine(f.read())
---> 59         self.context = self.engine.create_execution_context()
     60 
     61         if input_names is None:

AttributeError: 'NoneType' object has no attribute 'create_execution_context'

Photo of object_following directory:

<img width="314" alt="Screen Shot 2019-11-29 at 8 35 55 PM" src="https://user-images.githubusercontent.com/9034190/69894036-e1026f80-12e7-11ea-9859-7e675dd54f54.png">

**Comment by DennisFaucher** [comment]
I think this is related to issue https://github.com/NVIDIA-AI-IOT/jetbot/issues/126

**Comment by j-vara** [comment]
I have the same issue (AttributeError: 'NoneType' object has no attribute 'create_execution_context'), but not same error than issue #126. Any ideas?

**Comment by DennisFaucher** [comment]
The solution for me was to return the SparkFun JetBot and use the WaveShare JetBot. The SparkFun image has TensorRT 5.1 which is not compatible with the COCO model compiled for TensorRT 5.0.

**Comment by AK51** [comment]
I have the same problem, Is there any solution?
Note: I used the SD card image.

**Comment by AK51** [comment]
Does anyone have a solution? Thx
Do I need to use an older SD card image?

**Comment by santaimpersonator** [comment]
One of our customers found where a previous version of the images was being hosted. Here is a link to the [forum post](https://forum.sparkfun.com/viewtopic.php?f=88&t=51549&p=213052#p213052) with details on how to get it working. Hope this helps.

Sorry about that @DennisFaucher. I am still waiting to get help with updating that engine.

**Comment by lzty634158** [comment]
我的老镜像可以在B02最新板子上跑，但是就是B02板子HDMI无输出，升级最新镜像HDMI可以显示，但是模型错误跟楼主一样？
My old mirror can run on the B02 latest board, but is the B02 board HDMI no output, upgrade the latest mirror HDMI can be displayed, but the model error is the same as the building master?

**Comment by naisy** [comment]
You can download the latest ssd_mobilenet_v2_coco.engine from the following link.
https://github.com/NVIDIA-AI-IOT/jetbot/wiki/examples

JetBot SD Card Version | Model
-- | --
v0.3 | ssd_mobilenet_v2_coco.engine
v0.4 (latest) | ssd_mobilenet_v2_coco.engine

**Comment by xiepan610** [comment]
@DennisFaucher Hello! Have you solved your problem? I also have the problem,and I can't find only useful hlep on the net .Could you please give me a favor? Any help would be awesomely appreciated.

**Comment by santaimpersonator** [comment]
@xiepan610 There is an updated model, linked above, by @naisy.

@DennisFaucher I think this issue can be closed due to the updated engine model.

**Comment by DennisFaucher** [comment]
Thank you

**Comment by niiita** [comment]
Is there a coco engine that is compatible with tensorRT 6.0.1?
