### ISSUE TITLE
My jetbot’s PI OLED can't work and its motor light is red

### ISSUE THREAD

**Issue by YaoKong** [NVIDIA-AI-IOT/jetbot#167]
![IMG20191205132245](https://user-images.githubusercontent.com/58544765/70209813-29001700-176c-11ea-8117-aa2857389d04.jpg)
![IMG20191205132252](https://user-images.githubusercontent.com/58544765/70209827-2f8e8e80-176c-11ea-901d-6f1875b3f394.jpg)

![IMG20191205132245](https://user-images.githubusercontent.com/58544765/70209813-29001700-176c-11ea-8117-aa2857389d04.jpg)

**Comment by rakshitraj** [comment]
Check if you Flashed the correct image. It is ~21 gb when unzipped. Also which motor Drive are u using?
Give the IC number?
