### ISSUE TITLE
Hi, Quick question

### ISSUE THREAD

**Issue by Brayden1000** [NVIDIA-AI-IOT/jetbot#179]
I know this isn't an issue but had a quick question about the program overall. We are planning on using a jetson nano for image recognition for FIRST competition this year if anyone has heard of that and this looked promising but does it require internet after you train it? cause there is no internet out on the field. Any answers would be appreciated!

Thanks,
Brayden Coyer

**Comment by fernandozet** [comment]
You won't need internet after you train the model, it will run directly on the Jetson Nano.
