### ISSUE TITLE
Have VNC server in the image, and starting automatically at boot/login

### ISSUE THREAD

**Issue by fantauzzi** [NVIDIA-AI-IOT/jetbot#185]
Consider having a VNC server installed with the Ubuntu image for Jetbot, already configured to start at boot or login, _even when there is no display connected_. It should be possible to choose the resolution, and to disable/enable it. E.g. like what Raspbian does with REALVNC server.

Installing and configuring a VNC server on Jetbot is a pain in the side, as one can verify with a search on-line. Having it already installed and configured would improve the usability of the product.

**Comment by tokk-nv** [comment]
Hi fantauzzi,
Thank you for your suggestion.
VNC server is actually installed at the L4T level (BSP portion of JetPack).
You can find the README document on your Jetson Nano by going into `/media/jetbot/L4T-README/` and you will find `README-vnc.txt`.
