### ISSUE TITLE
"backwards" in basic motion should be "backward"

### ISSUE THREAD

**Issue by y2xiao** [NVIDIA-AI-IOT/jetbot#191]
In basic motion notebook the text

> The BasicJetbot class also has the methods right, forward, and backwards.

This should be

> The ``Robot`` class also has the methods right, forward, and ``backward``

**Comment by jaybdub** [comment]
y2xiao,

Thanks for pointing this out.  You're absolutely right.

An old vestige from when deliberating class names.

I'd be happy to accept a pull request that addresses this, otherwise will get around to correcting it soon.

Please let me know if you find any other issues.

Best,
John

**Comment by DingoOz** [comment]
I saw this little issue too, correction found in Pull request #347
