### ISSUE TITLE
Jetbot Teleoperation Index Error

### ISSUE THREAD

**Issue by liamhan0905** [NVIDIA-AI-IOT/jetbot#192]
I'm using a Xbox 360 controller and HTML5 Gamepad tester is recognizing it. However, when I run the script, I'm getting an stating that the tuple index is out of range... I have no clue how to go about fixing this. Anyone else have this issue?

![image](https://user-images.githubusercontent.com/44885838/77294850-2a653900-6ca2-11ea-8aeb-7cafd6478136.png)

![image](https://user-images.githubusercontent.com/44885838/77294790-10c3f180-6ca2-11ea-9a2c-2ca1ca912cfe.png)

**Comment by TCIII** [comment]
@liamhan0905,

I am using a XBox360 wired controller and the index is "0" like yours.

Did you do this "controller = widgets.Controller(index=1)  # replace with index of your controller" ?

Regards,
TCIII

**Comment by liamhan0905** [comment]
Yes,

I'm getting the errors below.. I'm getting many other errors on other projects too (object avoidance etc)

So, I'm thinking of reformatting my SD card and starting from scratch. I was wondering if "Create SD Card Image From Scratch" can be skipped if I just follow the Software Setup. Does the software setup have all dependant packages all installed (e.g. traitlets)



![image](https://user-images.githubusercontent.com/44885838/77864298-8ff28180-71dc-11ea-9e48-8dce3ec0ff06.png)

![image](https://user-images.githubusercontent.com/44885838/77864304-9bde4380-71dc-11ea-8ef9-af8c6a365005.png)

**Comment by jaybdub** [comment]
Hi liamhan0905,

Thanks for reaching out.

As @TCIII mentioned, you'll want to set the index to what the gamepad tester shows.  In your case this appears to be ``0`` so you would modify the line of code to read:

```python
controller = widgets.Controller(index=0)
```

Please let me know if this helps or you run into issues.

Best,
John
