### ISSUE TITLE
jetbot image can't output HDMI on new B02 board?

### ISSUE THREAD

**Issue by lzty634158** [NVIDIA-AI-IOT/jetbot#197]
jetbot image can't output HDMI on new B02 board?

**Comment by lingxiaiq** [comment]
I care about that too

**Comment by tokk-nv** [comment]
Hi lzty634158 and linxiaiq,

B01 revision Jetson Nano requires JetPack 4.3 based JetBot image, that is v0.4.0.
https://github.com/NVIDIA-AI-IOT/jetbot/releases/tag/v0.4.0

I just made it clear on our release page, I'm sorry if that was not clear.
Will you make sure that you use this updated version of the image?

We tested this on both A02 and B01 Dev Kit, and I just did it again on B01 and it worked.

**Comment by liamhan0905** [comment]
Hello, 

Will this B01-4.3 image be compatible with [ROS](https://github.com/dusty-nv/jetbot_ros)?

**Comment by lzty634158** [comment]
@tokk-nv After several autopilot training sessions, it was found that there was not enough memory？

**Comment by lzty634158** [comment]
只能重新烧写最新的镜像，重新配置环境解决此问题
