### ISSUE TITLE
JETBOT's graphics card

### ISSUE THREAD

**Issue by coffeezzzz** [NVIDIA-AI-IOT/jetbot#200]
How big is JETBOT's graphics card, and can it accommodate both obstacle avoidance and line detection

**Comment by tokk-nv** [comment]
JetBot is based on Jetson Nano, and it has a version NVIDIA Tegra X1 SoC which houses 128 CUDA cores for GPU.

You would need to experiment a bit, but there is a good chance that you can run obstacle avoidance and line detection at the same time, as that was demoed at GTC 2019.
https://www.youtube.com/watch?v=byGZt5ZYup0
