### ISSUE TITLE
About Errors in FaBo JetBot Kit

### ISSUE THREAD

**Issue by UMINODAIKI** [NVIDIA-AI-IOT/jetbot#203]
Hello. My name is Umino.
Please give us advice on the following items.
I have little experience. Please help me.

①About  Object Following - Live Demo

The following command at the beginning of the note

from jetbot import ObjectDetector
model = ObjectDetector ('ssd_mobilenet_v2_coco.engine')

I get the following error:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,) type'.
  _np_qint8 = np.dtype ([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,) type'.
  _np_quint8 = np.dtype ([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,) type'.
  _np_qint16 = np.dtype ([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,) type'.
  _np_quint16 = np.dtype ([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,) type'.
  _np_qint32 = np.dtype ([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,) type'.
  np_resource = np.dtype ([("resource", np.ubyte, 1)])

Is there any workaround? What I am interested in is the following command that I just entered in the terminal.
"pip3 install matplotlib"
”sudo apt-get install python-numpy python matplotlib ipython ipython-notebook python-pandas”
"sudo easy_install pandas"

② About PDF output
I am considering PDF output of Notebook, but I tried to install miktex, texlive, etc., but it is not possible to output from Jupiter.
Please let me know if you know the procedure.

③ Other
When I try to output the image from the camera by inputting the following command in Notebook, no error is output, but only the border line is displayed. If you know how to deal with it, please respond.

image = widgets.Image(format='jpeg', width=300, height=300)
display(image)

that's all. Please answer.

**Comment by akira-sasaki** [comment]
Hi, 
If you use JetBot image for JetPack v0.4(latest),  you must use ssd_mobilenet_v2_coco.engine for JetPack v0.4.

This is ssd_mobilenet_v2_coco.engine for JetPack v0.4.
https://drive.google.com/file/d/1KjlDMRD8uhgQmQK-nC2CZGHFTbq4qQQH/view

Please check this document.
https://github.com/NVIDIA-AI-IOT/jetbot/wiki/examples
