### ISSUE TITLE
jetbot object following can not run

### ISSUE THREAD

**Issue by hope450** [NVIDIA-AI-IOT/jetbot#204]
Program has been to stay in this code will not run down
model=Objectdetector('ssd_mobilenet_v2_coco.engine')

**Comment by tokk-nv** [comment]
Hi hope450,

If you are using JetBot sdcard image v0.4 (v0p4p0), based on JetPack 4.3, you must use the updated ssd_mobilenet_v2_coco.engine (with TensorRT packaged in JetPack 4.3)

Please check this document.
https://github.com/NVIDIA-AI-IOT/jetbot/wiki/examples#example-4---object-following

**Comment by xiepan610** [comment]
@tokk-nv  Hi! I  use the lastest ssd_mobilenet_v2_coco.engine,but it doesn't work.It still show a error,like this: AttributeError: 'NoneType' object has no attribute 'create_execution_context'. Could you help me solve this problem? Thank you very much!
