### ISSUE TITLE
Different image file

### ISSUE THREAD

**Issue by sreba** [NVIDIA-AI-IOT/jetbot#210]
what is the difference between "Jetson Nano Developer Kit SD Card Image",  and "NVIDIA DLI AI Jetson Nano SD Card Image v1.1.1"

**Comment by tokk-nv** [comment]
Hi sreba,
The DLI card image is based on the Jetson Nano Developer Kit SD Card Image, but has all the software components installed on top of it.

The JetBot card image is also prepared in the same way, but has even more software components (like TensorFlow).
You can check out how the JetBot card image is prepared.
https://github.com/NVIDIA-AI-IOT/jetbot/blob/master/scripts/run-script-and-save-log.sh

**Comment by sreba** [comment]
Thank you for your response.
