### ISSUE TITLE
Not connecting to camera

### ISSUE THREAD

**Issue by liamhan0905** [NVIDIA-AI-IOT/jetbot#211]
Did anyone get this issue before? 

Things were fine until recently and I can't connect to the camera anymore :(

![image](https://user-images.githubusercontent.com/44885838/82766655-97e23280-9dd5-11ea-90f0-143671fa77b9.png)

**Comment by tokk-nv** [comment]
Hi liamhan0905,

It is possible that the camera service hang so need to restart.
Would you try executing the following command on a terminal, restart the python kernel on the Jupyter notebook, then re-run?

```
sudo systemctl restart nvargus-daemon

**Comment by liamhan0905** [comment]
I just tried this and I'm getting the following error 

![image](https://user-images.githubusercontent.com/44885838/82768438-db439d80-9de3-11ea-9c68-8769b3408566.png)

**Comment by jaybdub** [comment]
Hi liamhan0905,

Thanks for reaching out.

Any luck getting past this issue?  If the camera is still hung, and was working previously, it's possible that it is a hardware issue (like loose connector) as well.

Best,
John

**Comment by Pranav-India** [comment]
camera.stop() solved the issue for me
