### ISSUE TITLE
Cannot get object following demo to work

### ISSUE THREAD

**Issue by jpiat** [NVIDIA-AI-IOT/jetbot#215]
Hi,

i'am using a jetson nano  developper kit and installed the jetbot repository at the latest version so that i can try different updated examples and modify for my robot platform. When trying the object following demo in the Jupyter Notebook, the kernel restart with no error message. Looking at the systemd service logs i get the following :

Jun 04 07:37:31 jetbot sh[3805]: [TensorRT] WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
Jun 04 07:37:31 jetbot sh[3805]: [TensorRT] ERROR: getPluginCreator could not find plugin FlattenConcat_TRT version 1 namespace
Jun 04 07:37:31 jetbot sh[3805]: [TensorRT] ERROR: Cannot deserialize plugin FlattenConcat_TRT
Jun 04 07:37:31 jetbot sh[3805]: [TensorRT] ERROR: getPluginCreator could not find plugin FlattenConcat_TRT version 1 namespace
Jun 04 07:37:31 jetbot sh[3805]: [TensorRT] ERROR: Cannot deserialize plugin FlattenConcat_TRT
Jun 04 07:37:37 jetbot sh[3805]: [I 07:37:37.892 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports

any idea on how to fix this ?

**Comment by jaybdub** [comment]
Hi jpiat,

Thanks for reaching out.

If you're not using the provided JetBot SD card image, this probably has to do with a version difference between the JetBot SD card image and the JetPack version your using.

The TensorRT engine for object detection is pre-compiled, and after that point is version dependent.  It may be possible to build it from scratch for your system.

Do you mind sharing the version of JetPack that you're using for your Jetson Nano?

Best,
John
