### ISSUE TITLE
is it possible use isaac in jetbot?

### ISSUE THREAD

**Issue by csc000** [NVIDIA-AI-IOT/jetbot#216]

**Comment by jaybdub** [comment]
Hi csc000,

Thanks for reaching out!

I would refer to the ISAAC documentation for steps on how to do this.  It would likely require creating a custom motor driver implementation.

You'll likely need to create a motor driver interface.  I believe Isaac already includes a codelet for Argus CSI cameras (which should include the IMX219 sensor used by JetBot).

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by csc000** [comment]
Done with motor driver implementation. Change camera to RealSense 435, also add IMU but differentialnavigation does not fully working - seems not exist wheel odometry.
