### ISSUE TITLE
I was Write ubuntu Image to my sdcard ,if I want install jetbot ,except again write jetbot image to sdcard?

### ISSUE THREAD

**Issue by jungyin** [NVIDIA-AI-IOT/jetbot#221]

**Comment by tomMEM** [comment]
Jetbot SD image contains Ubuntu, CuDa etc., thus just use the Jetbot SD image, it works nicely. T

**Comment by jaybdub** [comment]
Hi jungyin,

Thanks for reaching out!

If you need to modify an existing SD card, the following page may help

https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Create-SD-Card-Image-From-Scratch

It may be a bit outdated though.

Please let me know if this helps or you run into any issues.

Best,
John
