### ISSUE TITLE
Is this project compatible with Jetson TX1 since it is also based on Maxwell arch?

### ISSUE THREAD

**Issue by panpengjun** [NVIDIA-AI-IOT/jetbot#23]
Thanks!

**Comment by jaybdub** [comment]
Hi panpengjun,

The robot chassis itself is designed to fit the Jetson Nano, but many of the software components would still work.

Are you looking to use a particular piece of software from the project?

Best,
John

**Comment by panpengjun** [comment]
Hi John,

I am working on a project based on TX1, which involves a little bit of everything, including sonar sensors, motor, camera, etc. It uses ROS, which makes the code base relatively larger than your Nano project. I am wondering what needs to be done to duplicate this project on a TX1 since I don't have a Nano yet, just as a test drive.

PJ

**Comment by rangeli** [comment]
You would need a carrier board like the [Auvidea J90-LC](https://auvidea.eu/product/70761/).  You would also need to modify the chassis to fit that carrier board.  I'm not sure if the I/O on that board would be sufficient.  The power requirements will probably differ as well.  The other annoyance with the TX1 is storage: it has 16GB eMMC and no built-in card slot which may prove limiting.  It would be nice to see a fork of this project for the TX1, though.
