### ISSUE TITLE
Basic Motion Works Until I Attempt to "Link Motors to Triatlets"

### ISSUE THREAD

**Issue by WoulfHound** [NVIDIA-AI-IOT/jetbot#232]
Hi,

I have the SparkFun JetBot AI Kit, KIT-15365. Which according to their website has been retired.

I have been following the Basic Motion tutorial and now I am stuck. The lines of code that are run at the beginning of the tutorial function properly and the robot moves. Such as:
![image](https://user-images.githubusercontent.com/30272606/88724786-166e8f80-d0f9-11ea-8129-826f9b7418e9.png)
and
![image](https://user-images.githubusercontent.com/30272606/88724852-2f774080-d0f9-11ea-8ccb-f29bf4490e6b.png)
Once I get to the blocks of code under the "Link Motors to Triatlets" The robot remains unresponsive when the widgets are created and used after linking them to the traitlets.
![image](https://user-images.githubusercontent.com/30272606/88725147-a6acd480-d0f9-11ea-9c3c-0e400d3543e3.png)
The sliders do indeed appear and do indeed seem to function, however, they do not seem to be liked to the motors even after running both these two blocks of code.
Likewise, these to blocks of code have no response from the robot: 
![image](https://user-images.githubusercontent.com/30272606/88725350-fee3d680-d0f9-11ea-941f-342597935950.png)
Not sure what I am missing here, please help.

**Comment by santaimpersonator** [comment]
Hey there, you seem to be having an issue similar to issue #227. Try following the steps listed there.

**Comment by santaimpersonator** [comment]
@WoulfHound If this issue has been resolved, please close the issue.
