### ISSUE TITLE
bluethooth speaker doesnt work when called in Jupyterlab terminal

### ISSUE THREAD

**Issue by VegardIversen** [NVIDIA-AI-IOT/jetbot#239]
Hi,
I have a bluetooth speaker connected to my jetbot. When I run a python program in terminal on the jetson nano that uses the speaker it works with no problem. But when I run the same program from the terminal in jupyterlab (from the IP on the display), its just silent. Seems to be that jupyter are lacking access to use the bluetooth speaker or something, is there a fix for this?

Thank you in advance

**Comment by tokk-nv** [comment]
Hi VegardIversen,

Just to check, did you run the Python code on a notebook in Jupyter Lab?
How about if you open a Terminal in Jupyter Lab and run the python program?

**Comment by VegardIversen** [comment]
Hi @tokk-nv 
I did run it via the terminal in jupyter lab, and its not working...

**Comment by jaybdub** [comment]
Hi Vegardlversen,

Strange indeeed!  My understanding is that Jupyter is simply running a python kernel in the background.

Perhaps there is some issue with permissions, but I'm not sure at what level.

Are you able to share the exact commands you ran on each terminal, as well as perhaps the code (if possible).

Best,
John

**Comment by VegardIversen** [comment]
Hi John,
Sorry for late reply. I tested with many different audio libraries as playsound, sounddevice, pyaudio etc that works when i run it via terminal on the jetson nano but not when used via terminal in jupyterlab. example code
```
from gtts import gTTS
import playsound
def speak(text, language='en'):
    tts = gTTS(text=text, lang=language)
    filename = 'voice1.mp3'
    tts.save(filename)
    playsound.playsound(filename)
```
