### ISSUE TITLE
Battery requirements

### ISSUE THREAD

**Issue by johncrusso1** [NVIDIA-AI-IOT/jetbot#24]
What were the requirements when selecting the recommended battery? I have my Jetson connected to a different portable battery with 5v 2a USB ports via microusb and the Jetson powers on but then powers off after about 30 seconds. Could I see different results if I power via the barrel jack with a USB to barrel jack adapter?

**Comment by wujupi** [comment]
I think it is a wire problem, please try a shorter, better quality MicroUSB cable.

**Comment by einsteinagogo** [comment]
The battery in the BOM is NOW available in the UK via Amazon after discussions with Topstar (INIU)

https://amzn.to/2VRAwWC
