### ISSUE TITLE
Code Invalid in Wiki

### ISSUE THREAD

**Issue by gizmohd** [NVIDIA-AI-IOT/jetbot#25]
The code given in the Wiki is invalid and doesnt work. DLI_Jet_Demo

**Comment by jaybdub** [comment]
Hi Gizmohd,

Thanks for raising this issue.  Apologies, I believe the promotion code has expired.  We will update the Wiki to reflect this.

Instead, you can simply download and follow the [training notebook](https://github.com/NVIDIA-AI-IOT/jetbot/blob/master/notebooks/collision_avoidance/train_model.ipynb) on a system with PyTorch installed.  We've actually trained a collision model on Jetson Nano itself, which may be a fun starting point!

If you follow the step "install latest software" in the software setup, it should include the training notebook.  Be sure to download / backup any data you have collected before hand, just in case.

Please let me know if you run into any other issues :)

Thanks,
John

**Comment by gizmohd** [comment]
That’s crazy... device has been out a week and the code is expired?  ;)
