### ISSUE TITLE
What's the top speed of Jetbot?

### ISSUE THREAD

**Issue by ArtlyStyles** [NVIDIA-AI-IOT/jetbot#28]

**Comment by jaybdub** [comment]
Hi ArtlyStyles,

Thanks for reaching out.  We haven't done a quantitative test yet, but that would be cool to see!

The top speed is roughly near my walking pace, if that provides any reference.

If you decide to do test this quantitatively, let us know!  This may be helpful to others.

John

**Comment by ArtlyStyles** [comment]
Walking speed is about 3 mph.
