### ISSUE TITLE
Raspberry camera module V1.3 compatibility?

### ISSUE THREAD

**Issue by maximecb** [NVIDIA-AI-IOT/jetbot#29]
Hi,

I'm trying to get a camera module V1.3 working and struggling a little bit right now. The camera isn't showing up as '/dev/video0'. I'm using the default Jetson image (not the one specific to the jetbot project). I was wondering, are there specific packages I should install to make this work? Does the Jetson only work with the camera module V2?

**Comment by jaybdub** [comment]
Hi maximecb,

Unfortunately, there are not currently drivers for the OmniVision OV5647 sensor which the Raspberry Pi V1 camera uses.  The Sony IMX219 sensor, which the Raspberry Pi V2 uses, is supported though.  Here are some cameras using the IMX219 that should work with Jetson Nano:

1. [Raspberry Pi V2 Camera](https://www.amazon.com/Raspberry-Pi-Camera-Module-Megapixel/dp/B01ER2SKFS/ref=sr_1_3?keywords=raspberry+pi+v2+camera&qid=1554831689&s=electronics&sr=1-3)
2. [Raspberry Pi V2 Camera (NOIR)](https://www.amazon.com/RPi-Camera-V2-Official-Raspberry/dp/B07P7GBJTK/ref=sr_1_1_sspa?keywords=raspberry+pi+v2+camera&qid=1554831658&s=electronics&sr=1-1-spons&psc=1)
3. [Arducam IMX219 CS lens mount](https://www.robotshop.com/en/arducam-8mp-sony-imx219-camera-module-cs-lens-2718-raspberry-pi.html?gclid=EAIaIQobChMIzMKg38bD4QIVrR6tBh3UoAdjEAYYCSABEgLg-_D_BwE)
4. [Arducam IMX219 M12 lens mount](https://www.robotshop.com/en/arducam-8mp-sony-imx219-camera-module-m12-lens-ls40136-raspberry-pi.html)
5. [LI-IMX219-MIPI-AF-NANO](https://leopardimaging.com/product/li-imx219-mipi-af-nano/)
6. [LI-IMX219-MIPI-FF-NANO](https://leopardimaging.com/product/li-imx219-mipi-ff-nano/)

There may be more out there. 

Hope this helps!

John

**Comment by maximecb** [comment]
Thank you for the quick answer. I'll acquire a camera module V2.

**Comment by DragonBeanJL** [comment]
I'm looking for a wide angle (170 degree) camera module for my jetson nano :( Maybe I'll wait a little bit longer

**Comment by jaybdub** [comment]
Hi @DragonBeanJL,

The Arducam IMX219 boards listed above actually support custom lens configurations.

They're a bit more expensive, but may be worth it depending on your use case.  There is also a neat M12 lens kit you could play around with to evaluate different FOV lenses.

http://www.arducam.com/arducam-m12-mount-lens-kit-raspberry-pi-arduino-cameras/

Hope this helps :)

John

**Comment by DragonBeanJL** [comment]
@jaybdub Thanks for the info! It's a definitely good module if price isn't a concern. I actually digged around taobao and found this lens for the raspberry pi v2. 
[https://item.taobao.com/item.htm?spm=a1z09.2.0.0.4cbd2e8dMj04JO&id=576226489431&_u=g225cudh0da8]
Just bought it and waiting for shipment. Hope it works.

**Comment by filmo** [comment]
It would be nice if there was a driver for the much, much more prevalent OV5647 sensor. The installed base of these sensors far dwarfs the newer (and much more expensive IMX219 cameras). Probably by several orders of magnitude. 

Particularly if you need a wider FOV. To realistically get a Pi V2 + Wide angle lens is about $45 to $50 where as the older OV5647 with wide FOV can be had for between $15 and $20. Given that the Nano is $100, spending an additional $50 for a new camera rather than repurposing the older generation seems misguided. 

I think Nano should aim for 'drop-in-replacement' ready status vs RaspBerry Pi, but that's obviously just my opinion.

**Comment by maximecb** [comment]
I agree with filmo. You can even get a camera V1 clone for 7 dollars on ebay. It would be great if these worked with the Jetson.

**Comment by krukhlis** [comment]
Give a try and ask this guy https://devtalk.nvidia.com/default/topic/1025036/jetson-tx2/libargus-and-gstreamer-not-working-with-ported-ov5647-driver/ 
He was able to port it to jetson-tx2 -- should be possible to port it to the Jetson Nano as well.
Also, these guys are selling ported driver for Jetson-tx1
https://developer.ridgerun.com/wiki/index.php?title=OmniVision_OV5647_Linux_driver_for_Jetson_TX1
So I mean it shouldn't be anything impossible for Nvidia are comunity to port it.

**Comment by maximecb** [comment]
It would be great to have official support that comes built into the Ubuntu image supplied by nvidia.

**Comment by krukhlis** [comment]
The problem is not with the sensor support from the linux side. You can check, Linus git already has i2C driver for the sensor https://github.com/torvalds/linux/blob/master/drivers/media/i2c/ov5647.c
As far as I understood from different sources, e.g. https://www.raspberrypi.org/forums/viewtopic.php?t=54297 :
The problem is actual cameras with CSI2 interface. These cameras are created for RPI, unfortunately, RPI's CSI2 interface is controled by Broadcom GPU and the drivers for this GPU are proprietary and not available to public. That's one of the reasons why nobody wants to spend his time trying to reverse engineer or hack this RPIs drivers. 
Just compare with position from Sony -- they are more than happy to sell as much outdated sensors as possible, especially  considering such unexpected by their marketing guys interest from micro-boards comunity. That's why they are making available all possible specs for their sensor and interfaces  -- just buy the stock. :)

**Comment by dlarue** [comment]
What is motivating NVidia to NOT support the OmniVision_OV5647 sensor and sticking with ONLY supporting the Sony sensor?  This has been asked about as far back as the TX1 and a number of people have shown a driver can be provided.  Now that I know it can be done, I'm more concerned with NVidia's motivation for not supporting such a common device.  Maybe something about the Sony sensor allows for better marketing benchmarks? I would rather use a tool than be treated as one...

https://developer.ridgerun.com/wiki/index.php?title=OmniVision_OV5647_Linux_driver_for_Jetson_TX1

**Comment by maximecb** [comment]
I'm going to assume it has to do with:
- They think the sensor V2 is obviously better and so they don't care for the V1
- At nvidia and in silicon valley, money is no issue, so they don't understand how cheaper can be better
- People at nvidia being busy and not wanting to put in the (potentially tedious) work

IMO supporting the raspi camera V1 only makes the Jetson Nano a better platform, and should definitely be done. The amount of support in this thread makes it clear that this is something the users want.

**Comment by mtx512** [comment]
FYI We are writing a ov5647 driver for the nano and currently testing with v1.3 camera. See our [post](https://devtalk.nvidia.com/default/topic/1056106/jetson-nano/ov5647-driver-testing-with-v1-3-rpi-camera/).

**Comment by maximecb** [comment]
@mtx512 If you could also make this work in OpenCV without needing to compile with gstreamer support, that would be great.

**Comment by mtx512** [comment]
Alpha release of v1.3 camera (ov5647) driver is available [here](url=https://jas-hacks.blogspot.com/2019/08/jetson-nano-developing-pi-v13-camera.html).

**Comment by tr1pzz** [comment]
It also doesn't support Raspberry camera V3...
Kind of constraining that it has to be a V2 to work

**Comment by deomaximo** [comment]
> I agree with filmo. You can even get a camera V1 clone for 7 dollars on ebay. It would be great if these worked with the Jetson.

i wish i knew this before i bough it.

**Comment by Hagar-Usama** [comment]
> It would be nice if there was a driver for the much, much more prevalent OV5647 sensor. The installed base of these sensors far dwarfs the newer (and much more expensive IMX219 cameras). Probably by several orders of magnitude.
> 
> Particularly if you need a wider FOV. To realistically get a Pi V2 + Wide angle lens is about $45 to $50 where as the older OV5647 with wide FOV can be had for between $15 and $20. Given that the Nano is $100, spending an additional $50 for a new camera rather than repurposing the older generation seems misguided.
> 
> I think Nano should aim for 'drop-in-replacement' ready status vs RaspBerry Pi, but that's obviously just my opinion.
Would [this](https://developer.ridgerun.com/wiki/index.php?title=OmniVision_OV5647_Linux_driver_for_Jetson_Nano) help?

**Comment by dlarue** [comment]
But Hagar, don't you know you can purchase wide angle lens' for the v2 cameras and create your own wide FOV camera for just another $25? LOL

If you don't absolutely NEED the CUDA or GPU of the Nano, the rPi 4 will do the trick with far better hardware and software support.  it was insane that NVidia expected everyone to bolt a display, keyboard and mouse onto the Nano to configure it for networking and to get ssh going.

It seems the one or two people NVidia has working on the Linux software for the Nano,etc are quite over loaded. ;-)

**Comment by Hagar-Usama** [comment]
> But Hagar, don't you know you can purchase wide angle lens' for the v2 cameras and create your own wide FOV camera for just another $25? LOL
> 
> If you don't absolutely NEED the CUDA or GPU of the Nano, the rPi 4 will do the trick with far better hardware and software support. it was insane that NVidia expected everyone to bolt a display, keyboard and mouse onto the Nano to configure it for networking and to get ssh going.
> 
> It seems the one or two people NVidia has working on the Linux software for the Nano,etc are quite over loaded. ;-)

You're quite right. I am just trying to make use of what I already have.

**Comment by OrsoEric** [comment]
I was really surprised Jatson Nano doesn't support anything BUT the raspicam V2. Especially for the 2GB developer kit I expected it would be compatible with the cheaper camera modules.
