### ISSUE TITLE
Setup of USB wifi Dongle

### ISSUE THREAD

**Issue by nateislas** [NVIDIA-AI-IOT/jetbot#31]
I'm having trouble setting up the dongle. I flashed it on a mac and plugged the dongle into my Jetson Nano and my network is showing up but it still won't connect.

**Comment by tokk-nv** [comment]
Hi natethegreat19,
It is possible that L4T does not include the matching kernel module for your USB Wi-Fi dongle chipset.
Will you share the model name of the Wi-Fi dongle or the result of `lsusb`?
