### ISSUE TITLE
tensorrt destroy method not found

### ISSUE THREAD

**Issue by jaybdub** [NVIDIA-AI-IOT/jetbot#313]
From this post

https://forums.developer.nvidia.com/t/tensorrt-tensorrt-runtime-object-has-no-attribute-destroy/155079/4

TensorRT Python API no longer includes the ``destroy()`` method.  

The wrapper class should determine which TensorRT version is used, and handle excluding this.

**Comment by mfoglio** [comment]
Hi @jaybdub , what do you mean by wrapper class? Is there no way to explicitly destroy the engine? Is this left to the garbage collector?
