### ISSUE TITLE
handling the new version of Waveshare board

### ISSUE THREAD

**Issue by Ryan-ZL-Lin** [NVIDIA-AI-IOT/jetbot#316]
@tokk-nv san
I noticed that you have committed motor.py 2 days ago with handling the new version of Waveshare board, does that mean I could directly clone this repository here and spin the motor from Waveshare jet to kit?

 Before this commit, I have to replace the whole jetbot repository with Waveshare’s jetbot repository to spin the motor.

**Comment by tokk-nv** [comment]
Hi Ryan-ZL-Lin,

> does that mean I could directly clone this repository here and spin the motor from Waveshare jet to kit?

Yes, you can follow this Docker based setup method.
http://jetbot.org/master/software_setup/docker.html

Or you can also download the SD card image.
http://jetbot.org/master/software_setup/sd_card.html

**Comment by Ryan-ZL-Lin** [comment]
Thanks @tokk-nv  san, it works and save me a lot of time integrating different version of jetbot repository.
