### ISSUE TITLE
Add Additional Vendor for PiOLED Header

### ISSUE THREAD

**Issue by wphuhn** [NVIDIA-AI-IOT/jetbot#32]
The PiOLED header has been unavailable from Adafruit and Amazon for quite some time, however SparkFun has a suitable substitute in stock (https://www.sparkfun.com/products/12792).  Could this be added to the wiki as an alternative?

**Comment by jaybdub** [comment]
Hi wphuhn,

Thanks for pointing this out!  This does look like a suitable alternative.  I've added it to the bill of materials as an alternate source.

Thanks!
John
