### ISSUE TITLE
[Solved - kinda] running "sudo shutdown now" returns sudo: shutdown: command not found in jupyterlab

### ISSUE THREAD

**Issue by grandwiz** [NVIDIA-AI-IOT/jetbot#321]
I have just setup the jetson nano,

When i access the terminal and try to enter a shutdown command I am met with this error:
sudo: shutdown: command not found

I got the image from here.

**Comment by grandwiz** [comment]
Solved, it works when I do it directly on the Nano or via SSH

**Comment by whmzsu** [comment]
I think the console on the jupyterlab launch is a restricted shell , some critical system shell cmds were hided.
