### ISSUE TITLE
  from jetbot import Robot ModuleNotFoundError: No module named 'jetbot'

### ISSUE THREAD

**Issue by grandwiz** [NVIDIA-AI-IOT/jetbot#322]
I have flashed a Jetbot image onto an SD card. 

I tested the BasicMotion test under Notebooks and following through that works.
I have written a basic pythons script just to test that I can run custom python scripts on it.

Now the problem I have is that when I try to run the script in Python 2 or 3, I get this error:
` Traceback (most recent call last):
  File "testScript.py", line 2, in <module>
    from jetbot import Robot
ModuleNotFoundError: No module named 'jetbot'
`

Here is the script:
```
import time
from jetbot import Robot

robot = Robot()

robot.forward(1)

time.sleep(1.0)
robot.stop()


```

**Comment by Comicboy** [comment]
If you would like to run your test script from the terminal (on the Nano) like `python3 testScript.py` then you should write:

`from jetbot.jetbot import Robot `

(because if I'm not mistaken the robot.py file is inside a folder called jetbot, which is also in a folder called jetbot)
