### ISSUE TITLE
Start up error

### ISSUE THREAD

**Issue by spy-maker** [NVIDIA-AI-IOT/jetbot#328]
Hi,
Everytime when I start up jetson nano I am getting this tegra-i2c 7000c400.i2c: no acknowledge from address 0x3c does anyone know how to fix this?

**Comment by tomMEM** [comment]
Hello, if you use HDMI-nano and keyboard directly on nano you might get this error message. 
If you use PC SSH terminal over Wifi to nano then this message does not appear. 
You have to activate the i2c protocol in this terminal or HDMI/keyboard to have i2c outside the docker container - now i2c is running only in the Docker container. 
More hints here: https://www.jetsonhacks.com/2019/07/22/jetson-nano-using-i2c/
T
