### ISSUE TITLE
USB cam cannot be found from Jupyter notebook environment

### ISSUE THREAD

**Issue by greennote** [NVIDIA-AI-IOT/jetbot#332]
Hi all,

# Phenomenon and reproduction

On these new environment,

- jetbot-042_nano-2gb-jp441.zip
- jetbot-042_nano-4gb-jp441.zip
- jetbot-041_nano-2gb-jp441.zip
- jetbot-041_nano-4gb-jp441.zip

USB cam cannot be found from Jupyter ipynb nor terminal. For example, no video0 device is listed on Jupyter terminal.

```sh
# ls /dev/v*
/dev/vcs  /dev/vcs1  /dev/vcs2  /dev/vcs3  /dev/vcs4  /dev/vcs5  /dev/vcs6  /dev/vcsa  /dev/vcsa1  /dev/vcsa2  /dev/vcsa3  /dev/vcsa4  /dev/vcsa5  /dev/vcsa6  /dev/vhci

/dev/vfio:
vfio
```
# Reason

The reason is too early startup of `containerd`.  `/dev/video*` attached to the container In `docker/jupyter/enable.sh` but USB initialization is not finished when the container starts.  As the result of this, no USB cams are connected to the container.

# Evidence

After restarting the container, USB cam can be found from inside of it. On the terminal of Jetson nano itself,

```sh
$ sudo docker stop jetbot_jupyter
$ sudo docker start jetbot_jupyter
 ```

and open Jupyter Notebook from browser. Now USB cam can be seen on ipynb and terminal.

# Resolution

One of the resolution is to add sleep statement to `/lib/systemd/system/containerd.service`.

```
[Unit]
Description=containerd container runtime
Documentation=https://containerd.io
After=network.target local-fs.target

[Service]
ExecStartPre=/bin/sleep 15    # this line is added
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/bin/containerd

Delegate=yes
KillMode=process
Restart=always
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
LimitNOFILE=1048576
# Comment TasksMax if your systemd version does not supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity

[Install]
WantedBy=multi-user.target
```

I believe that more essential resolution. Thanks!

**Comment by whmzsu** [comment]
Great job.
