### ISSUE TITLE
Issue with jetbot flash image 

### ISSUE THREAD

**Issue by ThefirstSysurp** [NVIDIA-AI-IOT/jetbot#334]
Hi I am trying to connect to my jetbot with Jupyter but my pioled won’t turn on and show me the IP address and instead stays blank. Am I missing something? It would be great if someone could help. Thanks!

**Comment by whmzsu** [comment]
Connect the  jetbot to a   monitor with hdmi or dp  cable ,use the keyboard and mouse to find out the ip address about the jetbot.
As the pioled , make sure the cables are right connected.
