### ISSUE TITLE
No motor movement with jetbot-041_nano-4gb-jp441 image

### ISSUE THREAD

**Issue by Jundor-y** [NVIDIA-AI-IOT/jetbot#337]
Using the jetbot-041_nano-4gb-jp441 image on a Waveshare Jetbot, the motors do not work.
```
from jetbot import Robot
robot = Robot()
robot.left(speed=0.3)
```
should cause the jetbot to turn left.
The issue is, that it does not move at all. Nothing in the basic_motion script will get the jetbot moving.

The jetbot itself if functioning and does move using the newer jetbot-042_nano-4gb-jp441 image, However, that image cannot train models, it fails at the step of transfering the model to the GPU for execution, hence the attempt to use the older image which trains just fine, but is unable to move.

**Comment by tokk-nv** [comment]
Hello Jundor-y,

> However, that image cannot train models, it fails at the step of transfering the model to the GPU for execution

It sounds like this is the real problem you are facing.
Would you create a new issue or edit the title of this issue to detail this issue?

> Using the jetbot-041_nano-4gb-jp441 image on a Waveshare Jetbot, the motors do not work.

You can find more information on this here.
https://github.com/NVIDIA-AI-IOT/jetbot/issues/314
