### ISSUE TITLE
tegra-i2c 7000c400.i2c: no acknowledge from address 0x3c

### ISSUE THREAD

**Issue by zouzhe1** [NVIDIA-AI-IOT/jetbot#343]
https://github.com/NVIDIA-AI-IOT/jetbot/issues/328
I have this problem same.

1. Why do you want to turn off external I2C by default? The previous image is normal.
2. Can't enter GUI desktop, what should I do? Connect to WiFi?
3. If I can't connect to WiFi, I can't SSH?
4. Don't you need a mouse, keyboard and HDMI monitor???

thanks

**Comment by zouzhe1** [comment]
Add one, I don’t  have use OLED

**Comment by zouzhe1** [comment]
find result。

sudo systemctl set-default graphical.target

**Comment by wzmzero** [comment]
I also have this problem same.

**Comment by akhmedov** [comment]
The same problem
