### ISSUE TITLE
Jupyter example with Jetson Inference?

### ISSUE THREAD

**Issue by villesau** [NVIDIA-AI-IOT/jetbot#345]
Would it be possible to get an example notebook with [Jetson Inference](https://github.com/dusty-nv/jetson-inference) ?

**Comment by tokk-nv** [comment]
Hi villesau,
We have not tested intaking any example from `jetson-inference`.
Are you interested in any specific example from that?
If to just test what it offers on the same hardware you have for JetBot, I believe you can just use the `jetson-inference`'s container to quickly test.

**Comment by villesau** [comment]
@tokk-nv Would be nice to get to try out object detection & segmentation in Jetbot Jupyter environment to control motors  etc. effortlessly.
