### ISSUE TITLE
enable swap not documented in docker setup

### ISSUE THREAD

**Issue by jaybdub** [NVIDIA-AI-IOT/jetbot#369]
The script ``scripts/enable_swap.sh`` enables 4GB of SWAP which enables best performance on all platfoms.  However, this is not included in configuration script, nor is it documented in the docker setup guide.

http://jetbot.org/master/software_setup/docker.html

**Comment by tokk-nv** [comment]
PR https://github.com/NVIDIA-AI-IOT/jetbot/pull/374 made.
