### ISSUE TITLE
Jetson Nano with LIDAR: cannot initialize USB port 

### ISSUE THREAD

**Issue by lchakman** [NVIDIA-AI-IOT/jetbot#400]
I am currently trying to build a LIDAR robot with RPLIDAR A1 and Jetson Nano following the guide below.

https://www.hackster.io/shahizat005/building-a-map-using-lidar-with-ros-melodic-on-jetson-nano-2f92dd

I have reached step 8 where I'm trying to initialize the USB port to connect the robot with the LIDAR. However, upon running

```ls -l /dev | grep ttyUSB```

I did not get any output, which I assume is not normal as ```ls``` should show the files in that directory from my understanding.

After that, I ran

```crw-rw----```

As it have stated in the guide. It should have outputs, however, an error occurred as follows.

```bash: crw-rw----: command not found```

Without initializing the USB port, I cannot read and modify the RPLIDAR with the port.

I am on JetPack4.4 with Ubuntu 18.04 installed.

Does anyone know how to fix this as I am a newbie to the linux and jetson nano development environment? Thanks for all the help!

**Comment by jaybdub** [comment]
Hi Ichakman,

Thanks for reaching out!

Are you using one of the JetBot SD card images (inside Jupyter Lab), or did you download one of the Jetson Nano JetPack SD cards and are running natively (without Jupyter Lab)?

Best,
John
