### ISSUE TITLE
'update is not defined'

### ISSUE THREAD

**Issue by mattmi91** [NVIDIA-AI-IOT/jetbot#403]
I have been stuck on this issue for 2 weeks now where I try to run the collision avoidance demo and at the bottom the camera.observe command I keep getting error update is not defined, the camera is working and is displaying what it sees in the little box but when I go to execute the rest of the code I get 'update is not defined' I am using jetson nano sd card image 2gb-jp45 I have tried every version and all have the same exact problem.. plz help ):
![update](https://user-images.githubusercontent.com/63423576/111087397-ca415580-84f7-11eb-99a2-e3b5a18abb63.JPG)

**Comment by jaybdub** [comment]
Hi @mattmi91 ,

Thanks for reaching out!

This error typically means that the function hasn't yet been defined in Python.

Are you able to share the rest of the contents of the notebook?  My initial guess is that this name might have a typo.

Please let me know if this helps or you have any questions.

Best,
John
