### ISSUE TITLE
Jetbot is too slow Unable to run data collection code on it.

### ISSUE THREAD

**Issue by Pranav-India** [NVIDIA-AI-IOT/jetbot#419]
Hello,
I am trying to run the data collection code for the road following task using the given notebook but the jetbot computation is too slow and I am not able to run any cell I checked the stats of the cpu-gpu usage using the jetson package below is the output I received can you tell me is there something I have done wrong or am I missing something? 

![WhatsApp Image 2021-04-03 at 11 15 08 AM](https://user-images.githubusercontent.com/55158029/113469810-3f0c0d80-946e-11eb-9f28-c6f393658903.jpeg)

Thank you.

**Comment by Srafington** [comment]
It looks like you are configured in low power mode (5W), you'll want to switch to high power mode by running 
sudo nvpmodel -m 0

**Comment by Pranav-India** [comment]
Thank you I did that , it solved the issue..
