### ISSUE TITLE
Readme.md Wiki links wrong

### ISSUE THREAD

**Issue by ShaunPrice** [NVIDIA-AI-IOT/jetbot#42]
The Wiki links on the readme.md page are pointing to:
https://github.com/NVIDIA-AI-IOT-private/jetbot/wiki
instead of:
https://github.com/NVIDIA-AI-IOT/jetbot/wiki

**Comment by jaybdub** [comment]
Hi ShaunPrice,

Thank you for pointing this out!  We've fixed the broken links.

Best,
John
