### ISSUE TITLE
Teleoperation Python Code

### ISSUE THREAD

**Issue by AnbuKumar-maker** [NVIDIA-AI-IOT/jetbot#437]
Hello
I am using Jupyter Notebook examples for Teleoperation.  Can some one give me the Python code to add into the existing Jupyter notebook where in I can control the motors in all directions and speed of the motors using PS3 joystick ? like left, right, forward, backward, speed increase, speed decrease so that its easy to turn in all directions and take photos

**Comment by tokk-nv** [comment]
Hi AnbuKumar-maker,

I believe the teleoperation example notebook pretty much demonstrates such left, right, forward and backward motions, but if you want to apply some fixed speed and change the speed by pressing some buttons, I think you can do that by something like this.

```
def increse_motorspeed(change):
    motor_speed = max(0.8, motor_speed + 0.1)

controller.buttons[6].observe(increse_motorspeed, names='value')
```
