### ISSUE TITLE
Speed issues with Waveshare 2GB Jetbot

### ISSUE THREAD

**Issue by thesaltymaker** [NVIDIA-AI-IOT/jetbot#443]
Hello,

How do I change the motor.py and robot.py to cut the speed applied to the motors on the Waveshare 2GB Jetbot by /10?  The wheels fly off if it's over 0.1 speed on the first 4 notebooks.  It jerks hard.  When I edit both files in the docker container from the website in the docker it has no impact on the notebooks, even after restarting the kernel for that notebook.  

Thanks,
-salty

**Comment by DingoOz** [comment]
Unfortunately the hardware design is the root cause of this.

You can try dropping the settings but of course, the smaller the duty cycle on the PWM for the motors, the less torque they have.

The real issue is that the motors are being fed 12V not 5V.
