### ISSUE TITLE
When Jetbot was running the autopilot project, Jetbot experienced a lag in image transmission

### ISSUE THREAD

**Issue by Bryantding** [NVIDIA-AI-IOT/jetbot#452]
Jetbot experienced a delay while executing  "camera.observe(execute, names='value') "code while I was executing the autopilot project.The delay is about a second or so.

**Comment by santaimpersonator** [comment]
I usually get about the same lag when running the collision avoidance example over WiFi. I have found a LAN cable reduces that to around 0.5 sec or a little better. I think the lag is a combination of the amount of resources used for the image processing/transmission (i.e. task prioritization *"magic"*) and probably a TCP protocol (vs UDP) used for the camera feed.
