### ISSUE TITLE
PiOLED display Waveshare Jetbot with 2GB JetsonNano not turning on on reboot

### ISSUE THREAD

**Issue by iyin-256** [NVIDIA-AI-IOT/jetbot#453]
I assembled the JetBot but the PiOLED display has never automatically turned on for me. I even reformatted the SD card and re-etched to make sure but nothing changed. The stats.py works correctly the PiOLED is just not turning on boot.

**Comment by xblend** [comment]
https://github.com/JetsonHacksNano/installPiOLED follow the mentioned steps, it will show eth0 IP address by default but you can replace eth0 with wlan0 in the stats.py file under pioled/ directory
