### ISSUE TITLE
Error in object detector for object following code

### ISSUE THREAD

**Issue by akulanaresh1** [NVIDIA-AI-IOT/jetbot#480]
![Object_following_error](https://user-images.githubusercontent.com/90301175/134454584-7b697ceb-ba66-4891-b7ef-198c8894e759.png)
I am getting error while running object following code, request to help me

**Comment by santaimpersonator** [comment]
If you are running Jetpack 4.5 that example won't work. You have to use a Jetpack 4.3 image to use that model; they haven't rebuilt one yet. There's several issues on this already: https://github.com/NVIDIA-AI-IOT/jetbot/issues/327#issuecomment-747284866

You can probably just close this issue and subscribe to repository for an update (my guess is that they'll post it in the [release notes](https://github.com/NVIDIA-AI-IOT/jetbot/releases/tag/v0.4.0)) or [update the documentation and get rid of the call out box](http://jetbot.org/master/examples/object_following.html)
