### ISSUE TITLE
OLED didn't work

### ISSUE THREAD

**Issue by Jzy0101** [NVIDIA-AI-IOT/jetbot#483]
After inserting the SD card and the power switching on, the LED light shine red normally. But the OLED screen does not display at all. How can I solve this problem? Is there a problem with the copied system?

**Comment by santaimpersonator** [comment]
It would probably help if you gave more details:

- The hardware for your Jetbot - which OLED screen are you using?
- Which image you are using
- If a monitor is connected does anything show up
- Have you tried at least re-flashing the image on the SD card (in case it was corrupted the first time you flashed it)?
