### ISSUE TITLE
NVPM ERROR when running nvpmodel -q

### ISSUE THREAD

**Issue by jomoengineer** [NVIDIA-AI-IOT/jetbot#49]
When running 'nvpmodel -q' in Step 6 - Configure power mode from the wiki NVPM ERROR is seen.

Ex:
<pre><code>
jetbot@jetbot:~$ sudo nvpmodel -m1
jetbot@jetbot:~$ nvpmodel -q
NV Power Mode: 5W
1
NVPM ERROR: Error opening /sys/kernel/nvpmodel_emc_cap/emc_iso_cap: 13
NVPM ERROR: failed to read PARAM EMC: ARG MAX_FREQ: PATH /sys/kernel/nvpmodel_emc_cap/emc_iso_cap
</code></pre>

I believe it needs to be run as sudo.

This does not show an error.
Ex: 
<pre><code>
jetbot@jetbot:~$ sudo nvpmodel -q
NV Power Mode: 5W
1
</pre></code>

**Comment by jaybdub** [comment]
Hi jomoengineer,

Thanks for pointing this out.  I'll test this change and update the Wiki.

Best,
John

**Comment by colabora001** [comment]
The wiki haven't been updated. FYI

**Comment by Kaju-Bubanja** [comment]
More than a year later and the issue still exists. I came here from: https://github.com/dusty-nv/jetson-inference/issues/334 and the nano crashes regularly
