### ISSUE TITLE
Jetbot four motor software setup

### ISSUE THREAD

**Issue by petex8989** [NVIDIA-AI-IOT/jetbot#496]
Hi, I am working on a project with the jetson nano and the robot I am working on has four motors connected to the motor driver. As the jetbot is normally, it is only programmed to use two motors. Is there any way to change the code to make it work with four motors? I have tried editing the robot.py in the jupyter editor, but I am not sure how to rebuild the code. Any changes I make in the editor does not get put into effect. How would I go about rebuilding the program? Thanks.

**Comment by santaimpersonator** [comment]
If you are using the newer images that utilize the docker container and only need to modify the `robot.py` and `motor.py` files:

1. You'll want to modify the files in the [`jetbot` folder](https://github.com/NVIDIA-AI-IOT/jetbot/tree/master/jetbot) on the Jetson Nano.
2. Then you'll need to disable the docker container, rebuild the docker container (to include the changes that you made), and re-enable the container (for the code to able to execute).
    * There are some instructions here: https://github.com/NVIDIA-AI-IOT/jetbot/tree/master/docker
    * I think the instructions from [my pull request](https://github.com/NVIDIA-AI-IOT/jetbot/pull/468) might be more useful for you. See here: https://github.com/sparkfun/jetbot/tree/update-Docker/docker#rebuilding-containers

If you have to modify the Python package for the motor driver, then it does get more complicated. Hopefully, I didn't miss any steps.
