### ISSUE TITLE
Compatible with JetPack 4.6 ?

### ISSUE THREAD

**Issue by jiapei100** [NVIDIA-AI-IOT/jetbot#505]
Just started test jetbot on my Nano 2G...
Wondering if it's Okay running on JetPack 4.6 ?

Cheers

**Comment by NikolaAndro** [comment]
Hello, I also have just flashed JetPack 4.6 for the purpose of having CUDA 10.2 on the Jetbot.

After reading the instructions (https://jetbot.org/master/software_setup/sd_card.html) I got confused. Does JetPack 4.6 already contain the Jetson Nano platform or we need to add that as well?

It seems that after flashing my piOLED is not working anymore as well. 

I also had to download torch manually.

There is no Jupyter Notebooks either. 

Are you having any of these issues?

Thanks
