### ISSUE TITLE
Hi, I have jetson 2gb and 4gb. both not booting. I used images for 2 gb and 4gb

### ISSUE THREAD

**Issue by ZangarKarabayev** [NVIDIA-AI-IOT/jetbot#506]
the nvidia picture is on the monitor and that's it
![WhatsApp Image 2021-12-21 at 11 15 14](https://user-images.githubusercontent.com/63534481/146875703-2466a95d-c514-4380-ac32-8d5dacebd2f6.jpeg)

**Comment by tokk-nv** [comment]
If this is just related to Jetson Nano Developer Kit, you may want to ask the question on this forum.
https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76

Please note that the general SD card image to boot Jetson Nano Developer Kit (JetPack image) and the JetBot SD card image are different.

**Comment by ZangarKarabayev** [comment]
hi. thanks for answering my question.  I solved with sdk manager

вт, 1 февр. 2022 г. в 22:40, Chitoku YATO ***@***.***>:
