### ISSUE TITLE
Where are current JetPack sdcard images? None links are working.

### ISSUE THREAD

**Issue by killdaclick** [NVIDIA-AI-IOT/jetbot#530]
Iv tried to download sdcard images for 2GB or 4GB version but newest 4.6.1 image link is not working nor any other from archive.
How to download sdcard images???

https://developer.nvidia.com/embedded/jetpack

https://developer.nvidia.com/jetson-nano-2gb-sd-card-image

https://developer.download.nvidia.com/embedded/L4T/r32_Release_v7.1/JP_4.6.1_b110_SD_Card/Jetson_Nano_2GB/jetson-nano-2gb-jp461-sd-card-image.zip?5IyeOiCV66Iv8feibhMIurkKlBaDigF2XHJp0hf6ZzI-UZ6iViLNH6j_KiVZ2Rec5I-QvhM7FEV52maAf0NASxMA7ZNHc5bQE6348ExpIHF6Hx-spjaIoKkWStcY0_rSPNt30v_YLt8iWXinDxY5FuwfuUdGbNwr5rzJo_n7xI2Fu6VNQ_o-Yty18utwxcfpCH67d1RBRq6lMQBzds0sREdr7uby0H0JAQc&t=eyJscyI6ImdzZW8iLCJsc2QiOiJodHRwczpcL1wvd3d3Lmdvb2dsZS5wbFwvIn0

**Comment by brianlmerritt** [comment]
Jetbot images are here https://jetbot.org/master/software_setup/sd_card.html

Jetson nano normal images are here https://developer.nvidia.com/embedded/downloads

Older nano normal images are here https://developer.nvidia.com/embedded/jetpack-archive

Note 4.6.1 will not boot unless you have first loaded a 4.5.1 image - after that it should work.

Hopefully this helps - I spent a week waiting for the downloads to start working again and then using the forums to track down a 4.5.1 image.
