### ISSUE TITLE
basic motion do not work correctly

### ISSUE THREAD

**Issue by ahforoughi** [NVIDIA-AI-IOT/jetbot#533]
Hi,
I have done everything according to the hardware setup section but I have used different motor drivers. (this model: TB6612 CJMCU)
Everything works well but when I use the basic motion notebook to move jetbot, the jetbot moves in the wrong direction. For example when I run ``` robot.left(speed=0.5)``` it goes forward. NO directions are working properly. 
I check the solders and circuits once again and it seems are all ok.
(I am using jetson nano 2GB)
Does anyone have any idea how can I fix this?

**Comment by naisy** [comment]
@ahforoughi 
Let's see the robot.py code.
https://github.com/NVIDIA-AI-IOT/jetbot/blob/636add1/jetbot/robot.py#L78
This sets the left motor to negative speed and the right motor to positive speed.
```
def left(self, speed=1.0):
    self.left_motor.value = -speed
    self.right_motor.value = speed
```

In your case:
```
robot.left(speed=0.5)
```
Moving forward means that the +- of the left motor is reversed, or the left motor is installed in the opposite direction.

Swap the +- wiring of the left motor or swap the direction of the left motor.

**Comment by ahforoughi** [comment]
> @ahforoughi Let's see the robot.py code. https://github.com/NVIDIA-AI-IOT/jetbot/blob/636add1/jetbot/robot.py#L78 This sets the left motor to negative speed and the right motor to positive speed.
> 
> ```
> def left(self, speed=1.0):
>     self.left_motor.value = -speed
>     self.right_motor.value = speed
> ```
> 
> In your case:
> 
> ```
> robot.left(speed=0.5)
> ```
> 
> Moving forward means that the +- of the left motor is reversed, or the left motor is installed in the opposite direction.
> 
> Swap the +- wiring of the left motor or swap the direction of the left motor.
@naisy 
Thanks, but I tried this, which did not affect the motor's rotation. 
I have changed the code in jetbot dir, and restarted the images during the software setup once more. 
Do we have to build the images from scratch?

**Comment by ahforoughi** [comment]
>

**Comment by ahforoughi** [comment]
> @ahforoughi
> 
> > Do we have to build the images from scratch?
> 
> I think, no need.
> 
> > Thanks, but I tried this, which did not affect the motor's rotation.
> 
> It's strange. I want to understand this correctly. If you swap the plus and minus, the motor will rotate in the opposite direction. Are you using special motors?
> 
> In basic motion, you can also operate the right, forward, and backward buttons. Do these all move forward?

No, it's not special motors. it is the same as the instruction.
and when the left command executes, it goes forward. when the forward command executes it goes to the right. it is like all of the directions are not working correctly.

**Comment by naisy** [comment]
@ahforoughi 

Change the wiring.
before:
![before](https://user-images.githubusercontent.com/8622180/163696842-b3baf7aa-4cfa-4765-ae43-54efb5bc5389.png)
after:
![after](https://user-images.githubusercontent.com/8622180/163696846-c11e26f9-995a-45f4-8755-9995318ea560.png)

> when the left command executes, it goes forward. when the forward command executes it goes to the right.

In the figure, you can see that the left and right motor connections are reversed.
After that, reverse the plus and minus of the right motor to make the correct connection.
![electric_current_control](https://user-images.githubusercontent.com/8622180/163696910-7d157c7a-e679-4250-8edf-639bb82143be.png)
