### ISSUE TITLE
JetBot Camera keeps rebooting Jetson Nano

### ISSUE THREAD

**Issue by Kivin1** [NVIDIA-AI-IOT/jetbot#536]
Hi

I am facing one issue. i am executing data collection script in collision avoidance,. Camera.instance() give me no response and after a while, the jetson nano will reboot. After rebooting, the issue still remain the same

The camera is working well when running nvgstcapture-1.0

Could you please help to check on this issue.

**Comment by Matthew-Hu-cmd** [comment]
I'm facing the same issue here, while running the veido proccing node along with other ROS nodes, it will reboot after a while...
but it worked like a charm if I only turn the navigation nodes up...

**Comment by Juff-Ma** [comment]
me to, please help. GSTream prints producer connected and the jetbot reboots

**Comment by Kivin1** [comment]
I am using jetcam as a workaround.. it works to me

**Comment by Juff-Ma** [comment]
Could you please give me a tutorial for this or example?

**Comment by jaybdub** [comment]
You can find the JetCam package and instructions [here](https://github.com/NVIDIA-AI-IOT/jetcam) 

Hope this helps.  Going to close for now.  Feel free to re-open if you run into any issues or have questions.

Best,
John
