### ISSUE TITLE
Jetson Nano not booting . Getting this screen . GUI is not displaying 

### ISSUE THREAD

**Issue by anandbharadwaj1** [NVIDIA-AI-IOT/jetbot#538]
![WhatsApp Image 2022-06-01 at 5 57 35 PM](https://user-images.githubusercontent.com/83603991/171404435-717b0285-4f92-450b-a42b-def31d874fa2.jpeg)

**Comment by ThaiVuz** [comment]
i also have a problem like you ? If you know how to fix it please help me !!!!

**Comment by moehammadtjakra** [comment]
configure_jetson.sh also disables the GUI for the interest of saving system memory (DRAM) consumption.
If you want to re-enable the GUI, you can execute the following command.


sudo systemctl set-default graphical.target
Optionally, you can execute this script (./scripts/re_enable_gui.sh).

**Comment by jaybdub** [comment]
Duplicate of https://github.com/NVIDIA-AI-IOT/jetbot/issues/538
