### ISSUE TITLE
Jetbot motor test

### ISSUE THREAD

**Issue by anandbharadwaj1** [NVIDIA-AI-IOT/jetbot#542]
We were able to run the motor.ipynb script from Jupiter notebooks. We would like to create a python file and run the motors and link with the other part of project which involves subscribing to data. Could you tell me how to create a python script for running the motors and run it using the command python motor.py.

**Comment by naisy** [comment]
Please refer to basic_motion.

a.py
```python
from jetbot import Robot
import time

robot = Robot()
robot.left(speed=0.3)
time.sleep(0.5)
robot.stop()
```
run
```
python3 a.py
```

**Comment by anandbharadwaj1** [comment]
Tried this but there is some issue with the i2c bus module

**Comment by naisy** [comment]
Is jetbot installed correctly?
Do you have error log?

**Comment by anandbharadwaj1** [comment]
Yes the installation of jetbot is done properly. We used a prebuilt jetbot image while flashing the SD card

**Comment by naisy** [comment]
Can you past these two logs?

1. check jetbot installed or not
```
pip3 list installed | grep jetbot
```

2. python error log
```
python3 -c 'from jetbot import Robot'
```
