### ISSUE TITLE
intel 3165 M.2 wireless ,how to use?

### ISSUE THREAD

**Issue by zouzhe1** [NVIDIA-AI-IOT/jetbot#57]
i download and extract,then i `cp iwlwifi-*.ucode /lib/firmware`
but  when i restat the nano,i can't see   the wifi  icon,only  wired options.

please help me.
thanks

**Comment by jaybdub** [comment]
Hi zouhzhe1, 

Thanks for reaching out!  Unfortunately, I don't have experience working with the Intel 3165 (we used the Intel 8265 for JetBot).

I would recommend opening a thread in our devtalk forums to reach a larger audience.

https://devtalk.nvidia.com/default/board/371/jetson-nano/

Best,
John
