### ISSUE TITLE
Suggestion for STL

### ISSUE THREAD

**Issue by zlite** [NVIDIA-AI-IOT/jetbot#6]
The little flashlight in the battery is a nice feature, but it's facing the wrong direction to be a headlight. Consider redesigning the case so it faces forward. 

I find that the CV works better with consistent lighting, and the light could help there.  Plus: cool headlight!

**Comment by tokk-nv** [comment]
Hi Chris, 
Thank you for your suggestion!
We actually looked at the option, but the USB cables coming out from the adjacent connectors got in the way of the camera's wide FoV, so we gave up.
The power bank actually comes with a separate USB torchlight, and we stuck into one of the USB ports on Jetson Nano Developer Kit and we could let JetBot follow a road in a dark!
So we can at least make use of that LED light.
