### ISSUE TITLE
Issues connecting to JetBot IP address

### ISSUE THREAD

**Issue by Mubeeni35** [NVIDIA-AI-IOT/jetbot#67]
Hello, I am having issues connecting to the IP address of the jetbot. I'm hooking it up using an ethernet connection as I don't have the usb wifi adapter yet. Does anyone know what I may be doing wrong or how to remedy this issue? Thanks

**Comment by wjzhou** [comment]
It will be easier if you can connect the a monitor and keyboard to the nano.

I used the ethernet before my wifi adapter arrived and it worked.

command to check the ip:
```
$ip addr show
```

**Comment by Mubeeni35** [comment]
I am having issues connecting my laptop to the jetbot using the IP address displayed on the PiOLED display. Does anyone know what could be wrong? thanks.

**Comment by hungnm2014** [comment]
I have same issues when connecting my laptop to jetbot using IP.
@Mubeeni35 : Did you connect ok? How to fix this?

Thanks

**Comment by Mubeeni35** [comment]
I changed my router and everything regarding connecting to the ip was fine after that.
