### ISSUE TITLE
The link to self tapping m2 screw in BoM is wrong?

### ISSUE THREAD

**Issue by TheNevers** [NVIDIA-AI-IOT/jetbot#70]
The amazon link to M2 screw in bill of material (http://amzn.com/B00YBMRAH4)
Currently points to "Hexagon Socket Cap Head Self Tapping Screws Fasteners M2x8mm" which is...wrong, I guess?

**Comment by einsteinagogo** [comment]
I prefer hex to normal flat heads for robot builds.

**Comment by jaybdub** [comment]
Hi,

Sorry for the confusion.  I believe we updated the screws to the hex screws listed in the BOM given the difficulty / long lead times of sourcing the flat head screws.

Either should work.

Best,
John
