### ISSUE TITLE
Bill of Materials/WiFi URLs: Mouser 

### ISSUE THREAD

**Issue by marc-medley** [NVIDIA-AI-IOT/jetbot#73]
Regarding the [WiFi Bill of Materials WiFi](https://github.com/NVIDIA-AI-IOT/jetbot/wiki/bill-of-materials#wifi), Mouser would also as an authorized supplier for [Intel 8265](http://www.mouser.com/access/?pn=8265.NGWMG) M.2 WiFi/BT modules and  [Molex 204281-1100 passive antennas](https://www.mouser.com/Search/Refine?Keyword=2042811100).

**Comment by jaybdub** [comment]
Hi marc-medley,

This is very good to know, thanks for pointing these out.

We'll look into this further and consider placing these vendor links in BOM if appropriate.

Best,
John
