### ISSUE TITLE
How to create JetBot AI car image 

### ISSUE THREAD

**Issue by yjhjstz** [NVIDIA-AI-IOT/jetbot#74]
How to reduce 60GB image ?

**Comment by jaybdub** [comment]
Hi,

Thanks for reaching out.  If you follow this page

https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Create-SD-Card-Image-From-Scratch

You should be able to create the SD card image from scratch.  This should work fine on any size of SD card > 32GB.  (16GB may work, but it would be close.)

Please let me know if you have any questions.

Best,
John
