### ISSUE TITLE
Motor Drive - Out of Stock

### ISSUE THREAD

**Issue by verissimomanoel** [NVIDIA-AI-IOT/jetbot#82]
Dear,
In the wiki page we have a Motor Driver to mount jetbot, but this product [()](https://www.adafruit.com/product/2927) is out of stock. Does have another Motor Drive to substitute?

**Comment by jaybdub** [comment]
Hi verissimomanoel,

Thanks for reaching out! 

It looks like the Motor Driver is available on Amazon, using [this link](https://www.amazon.com/Motor-Stepper-FeatherWing-Feather-Boards/dp/B01ABIB2UC/ref=as_li_ss_tl?ie=UTF8&qid=1549563340&sr=8-2-spons&keywords=adafruit+dc+motor+feather&psc=1&smid=A19MRELPGC5OXX&linkCode=sl1&tag=jbstore074-20&linkId=0cd3d112791e77148d8bf1ecef4ae514&language=en_US)

Please let me know if this works for you.

Best,
John
