### ISSUE TITLE
Jetbot Direction

### ISSUE THREAD

**Issue by CLUE72** [NVIDIA-AI-IOT/jetbot#90]
I have a problem with the Jetbot in the Notebook Basic Motion:
if I click on the forward button the jetbot goes to the casterball and if I press backward it goes to the wheels. If I press right CCW if I press Left CW.
In Collision Avoidance - Live Demo
Jetbot goes to the casterball and crash with all. 
![jetbot4 redimensionado](https://user-images.githubusercontent.com/51923729/59622754-bace8600-9132-11e9-9892-4fdbed7229e3.jpg)
![jetbot1 redimensionado](https://user-images.githubusercontent.com/51923729/59622764-c0c46700-9132-11e9-8c7a-462088fff64f.jpg)

It seems that the engines are connected the same as in https://github.com/NVIDIA-AI-IOT/jetbot/wiki/hardware-setup
Some explanation. Thanks in advance

**Comment by jaybdub** [comment]
Hi CLUE72,

Thanks for reaching out.  Sorry, as mentioned in the quote [here](https://github.com/NVIDIA-AI-IOT/jetbot/wiki/hardware-setup#step-5---mount-motor-driver), the motor wires are reversed in the image.  Can you try flipping the red / black wires of each motor as depicted below

![Capture](https://user-images.githubusercontent.com/4212806/59631986-fb5fdc80-90fd-11e9-9154-7615ab51e643.PNG)

Please let me know if you have any questions. 

Thanks!
John

**Comment by CLUE72** [comment]
Thanks now it works fine

**Comment by mauroesposito** [comment]
Hiu @jaybdub ,
thank you for tip! 
Why no one update images on official documentation on hardware build steps?
m
